command:
  - python
  - launcher.py

env:
  - name: PGHOST
    valueFrom: usage-limits-db
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: LAKEBASE_INSTANCE
    value: "usage-limits"
  - name: SQL_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: EVALUATION_INTERVAL_MINUTES
    value: "5"
  - name: BUDGET_API_PORT
    value: "8502"
  - name: OTEL_TABLE
    value: ""
